quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('form/', views.FormView.as_view(), name='form'),
    path('forms/', views.create_quote, name='create_quote'),
    path('filterquote/', views.quote_view, name='quote_view'),
    path('filtersource/', views.source_view, name='source_view'),
]

quotessite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quotes/', include('quotes.urls'))
]

quotes/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Source(models.Model):
    TYPE_CHOICES = [
        ('1' , "Tweet"),
        ('2' , 'Article'),
        ('3' , "Podcast"),
        ('4' , "Not Specfied"),
    ]
    type_text = models.CharField(max_length = 20, choices = TYPE_CHOICES, default='4')
    url = models.URLField(max_length=200)
    title_text = models.CharField(max_length=200)
    description_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('published at')

    def __str__(self):
        return self.title_text

class Quote(models.Model):
    quote_text = models.CharField(max_length=200)
    author_text = models.CharField(max_length=200)
    CHOICES = [
        ('-1' , "Negative"),
        ('1' , "Positive"),
        ('0' , "Neutral"),
    ]
    sentiment = models.CharField(max_length = 8, choices = CHOICES, default='0')
    create_date = models.DateTimeField('created at')
    source = models.ForeignKey(Source, on_delete=models.CASCADE)

    def __str__(self):
        return self.quote_text

quotes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse
from django.utils import timezone

from .models import Quote, Source

class IndexView(generic.ListView):
    template_name = "quotes/index.html"
    context_object_name = "quotes_list"

    def get_queryset(self):
        return Quote.objects.all()

class DetailView(generic.DetailView):
    model = Quote
    template_name = "quotes/detail.html"

    def get_queryset(self):
        return Quote.objects.all()

class FormView(generic.ListView):
    template_name = "quotes/form.html"

    def get_queryset(self):
        return 
    

def create_quote(request):
    if request.method == "POST":
        quotetext = request.POST.get('qtext', '')
        author_name = request.POST.get('author_name', '')
        outlook_value = request.POST.get('outlook_value', '')
        created_at = timezone.now()

        source_type = request.POST.get('source_type', '')
        link = request.POST.get('link', '')
        source_name = request.POST.get('source_name', '')
        description = request.POST.get('description', '')
        pubdate = timezone.now()

        # Save source
        s = Source(
            type_text=source_type,
            url=link,
            title_text=source_name,
            description_text=description,
            pub_date=pubdate
        )
        s.save()

        q = Quote(
            quote_text=quotetext,
            author_text=author_name,
            sentiment=outlook_value,
            create_date=created_at,
            source=s
        )
        q.save()

        return HttpResponseRedirect(reverse('quotes:index'))

    return render(request, 'quotes/form.html')


def quote_view(request):
    selected_value = request.POST.get('quotetypes')

    if selected_value == '2' or selected_value is None:
        quotes = Quote.objects.all()
    else:
        quotes = Quote.objects.filter(sentiment=selected_value)

    return render(request, 'quotes/index.html', {
        'quotes_list': quotes,
        'selected_value': selected_value
    })

def source_view(request):
    selected_value = request.POST.get('sourcetypes')

    if selected_value == '5' or selected_value is None:
        quotes = Quote.objects.all()
    else:
        quotes = Quote.objects.filter(source__type_text = selected_value)

    return render(request, 'quotes/index.html', {
        'quotes_list': quotes,
        'selected_value': selected_value
    })

quotes/templates/quotes/detail.html
<h1> Quote Info </h1>
<ul>
    <li>{{ quote.quote_text }}</li>
    <li>Author Name: {{ quote.author_text }}</li>
    <li>{{ quote.get_sentiment_display }}</li>
    <li>{{ quote.create_date}}</li>
    <li>{{ quote.source}}</li>
</ul>

<h1>Source</h1>
<ul>
    <li>{{ quote.source.get_type_text_display }}</li>
    <li><a href = "{{ quote.source.url }}">{{ quote.source.url }}</a></li>
    <li>{{ quote.source.title_text }}</li>
    <li>{{ quote.source.description_text }}</li>
    <li>{{ quote.source.pub_date }}</li>
</ul>
<a href = "/quotes"> Back </a>

quotes/templates/quotes/form.html
<h1> Add Your Things Here </h1>
<h3>Info for Source and Quote</h3>
<form action="{% url 'quotes:create_quote' %}" method="post">
  {% csrf_token %}
  <label for="qtext">Quote Text</label>
  <input type="text" id="qtext" name="qtext"><br><br>
  <label for="author_name">Author's Full Name</label>
  <input type="text" id="author_name" name="author_name"><br><br>
  <p1> Type: -1 for Negative | 0 for Neutral | 1 for Positive <p1><br><br>
  <label for="outlook_value">Outlook</label>
  <input type="text" id="outlook_value" name="outlook_value"><br><br>
  <p1> Type: 1 for Tweet | 2 for Article | 3 for Podcast | 4 for Not Specified <p1><br><br>
  <label for="source_type">Type of Source</label>
  <input type="text" id="source_type" name="source_type"><br><br>
  <label for="link">Link</label>
  <input type="text" id="link" name="link"><br><br>
  <label for="source_name">Source Title</label>
  <input type="text" id="source_name" name="source_name"><br><br>
  <label for="description">Description</label>
  <input type="text" id="description" name="description"><br><br>
  <input type="submit" value="Submit">
</form>

<a href = "/quotes"> Back </a>

quotes/templates/quotes/index.html
<div class="filter">
<form method="post" action="{% url 'quotes:quote_view' %}">
    {% csrf_token %}
    <label for="quotetypes">Type of Quote:</label>
    <select name="quotetypes" id="quotetypes">
        <option value="2" {% if selected_value == '2' or selected_value is None %}selected{% endif %}>All</option>
        <option value="1" {% if selected_value == '1' %}selected{% endif %}>Positive</option>
        <option value="0" {% if selected_value == '0' %}selected{% endif %}>Neutral</option>
        <option value="-1" {% if selected_value == '-1' %}selected{% endif %}>Negative</option>
    </select>
    <button type="submit">Submit</button>
</form>

<form method="post" action="{% url 'quotes:source_view' %}">
    {% csrf_token %}
    <label for="sourcetypes">Type of Source:</label>
    <select name="sourcetypes" id="sourcetypes">
        <option value="5" {% if selected_value == '5' or selected_value is None %}selected{% endif %}>All</option>
        <option value="4" {% if selected_value == '4' %}selected{% endif %}>Not Specified</option>
        <option value="3" {% if selected_value == '3' %}selected{% endif %}>Podcast</option>
        <option value="2" {% if selected_value == '2' %}selected{% endif %}>Article</option>
        <option value="1" {% if selected_value == '1' %}selected{% endif %}>Tweet</option>
    </select>
    <button type="submit">Submit</button>
</form>
</div>

<h1> Quote List </h1>
{% if quotes_list %}
    <ul>
    {% for quote in quotes_list %}
        <li><a href = "{% url 'quotes:detail' quote.id %}">{{ quote.quote_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p> No quotes here</p>
{% endif %}

<a href="{% url 'quotes:form' %}">Add Quotes Here</a>